name: MUtils-Timer
load: STARTUP
version: 111
main: de.miraculixx.mtimer.MTimer
api-version: 1.16
authors: [ Miraculixx ]
description: MUtils Timer - Stop your time or use it as a countdown. Personal Timers, Goals, Rules and more!
website: https://mutils.net/
softdepend:
  - "MUtils-Challenge"
libraries:
  - "org.jetbrains.kotlin:kotlin-stdlib:1.9.22"
  - "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.8.0-RC2"
  - "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8:1.8.0-RC2"
  - "org.jetbrains.kotlinx:kotlinx-serialization-json:1.6.2"
  - "org.yaml:snakeyaml:2.2"
  - "io.ktor:ktor-client-core:2.1.3"
  - "io.ktor:ktor-client-cio:2.1.3"
  - "dev.jorel:commandapi-bukkit-shade:9.3.+"
  - "dev.jorel:commandapi-bukkit-kotlin:9.3.+"

