name: MUtils-Timer
load: STARTUP
version: 111
main: de.miraculixx.mtimer.MTimer
api-version: 1.16
authors: [ Miraculixx ]
description: MUtils Timer - Stop your time or use it as a countdown. Personal Timers, Goals, Rules and more!
website: https://mutils.net/
softdepend:
  - "MUtils-Challenge"
libraries:
  - "org.jetbrains.kotlin:kotlin-stdlib:1.9.0"
  - "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.2"
  - "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8:1.7.2"
  - "org.jetbrains.kotlinx:kotlinx-serialization-json:1.4.1"
  - "io.ktor:ktor-client-cio-jvm:2.3.2"
  - "io.ktor:ktor-client-core-jvm:2.3.2"
  - "org.yaml:snakeyaml:1.33"
  - "dev.jorel:commandapi-bukkit-shade:9.2.0"
  - "dev.jorel:commandapi-bukkit-kotlin:9.2.0"

