name: 'MUtils-Challenge'
load: STARTUP
version: 112
main: 'de.miraculixx.mchallenge.MChallenge'
api-version: '1.20'
authors:
  - 'Miraculixx'
  - 'NoRisk'
description: 'MUtils Challenges - Play various Challenges that can modify the game slightly to completely against or in coop with your friends!'
website: 'https://mutils.net/'
softdepend:
    - MUtils-Timer
    - MUtils-Web
libraries:
  - "org.jetbrains.kotlin:kotlin-stdlib:1.9.22"
  - "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.8.0-RC2"
  - "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8:1.8.0-RC2"
  - "org.jetbrains.kotlinx:kotlinx-serialization-json:1.6.2"
  - "org.yaml:snakeyaml:2.2"

commands:
  mobhunt:
    permission: mutils.command.mobhunt
    description: Modify the Mob-Hunt challenge
  itemhunt:
    permission: mutils.command.itemhunt
    description: Modify the Item-Hunt challenge